import type { ComponentType } from "react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { ArrowLeft, BookOpen, CheckCircle2, Lightbulb, ShieldAlert, Target } from "lucide-react";
import { getDashboardIncidentDetail } from "@/lib/aegisops";
import { PageTitle, Panel, StatusBadge, formatDate } from "@/components/ui";

export const instant = false;

export default async function PostmortemDetailPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params;
  const incidentId = Number(id);
  const detail = Number.isInteger(incidentId) ? await getDashboardIncidentDetail(incidentId) : null;
  if (!detail?.postmortem) notFound();
  const postmortem = detail.postmortem;

  return (
    <div className="mx-auto max-w-[1500px]">
      <Link href="/postmortems" className="mb-5 inline-flex items-center gap-2 text-xs font-black text-[#6f747e] hover:text-[#111625]"><ArrowLeft className="h-4 w-4" />Back to postmortems</Link>
      <PageTitle eyebrow={`Incident #${detail.incident.id}`} title={detail.incident.title} description={`Postmortem generated by ${postmortem.model}. Updated ${formatDate(postmortem.updated_at)}.`} actions={<><StatusBadge text={detail.incident.severity} tone={detail.incident.severity === "HIGH" || detail.incident.severity === "CRITICAL" ? "red" : "amber"} /><StatusBadge text={detail.incident.status} tone="green" /></>} />

      <Panel className="relative overflow-hidden p-7"><div className="absolute -right-10 -top-10 h-44 w-44 rounded-full bg-[#fdebf5]" /><div className="relative z-10 flex items-start gap-4"><div className="flex h-14 w-14 shrink-0 items-center justify-center rounded-[20px] bg-[#fdebf5]"><BookOpen className="h-6 w-6 text-[#c73f82]" /></div><div><p className="text-[10px] font-black uppercase tracking-[.14em] text-[#999ca3]">Executive Summary</p><p className="mt-3 max-w-5xl text-base leading-7 text-[#505560]">{postmortem.summary}</p></div></div></Panel>

      <section className="mt-5 grid gap-5 lg:grid-cols-2">
        <ContentCard icon={Target} title="Impact" text={postmortem.impact ?? "No impact summary stored."} tone="blue" />
        <ContentCard icon={ShieldAlert} title="Probable Root Cause" text={postmortem.root_cause ?? "Undetermined from available evidence."} tone="red" />
        <ContentCard icon={CheckCircle2} title="What Went Well" items={postmortem.what_went_well} tone="green" />
        <ContentCard icon={ShieldAlert} title="What Could Be Improved" items={postmortem.what_went_wrong} tone="amber" />
        <ContentCard icon={Lightbulb} title="Lessons Learned" items={postmortem.lessons_learned} tone="pink" />
      </section>

      <Panel className="mt-5 p-6"><div className="flex items-center justify-between"><div><p className="text-lg font-black">Preventive Actions</p><p className="mt-1 text-xs text-[#8b8e96]">Recommended follow-up work retained in incident memory</p></div><Lightbulb className="h-5 w-5 text-[#c73f82]" /></div><div className="mt-5 grid gap-4 lg:grid-cols-2">{postmortem.preventive_actions.map((action, index) => { const object = typeof action === "string" ? null : action; return <div key={index} className="rounded-[22px] bg-white/58 p-5"><p className="text-sm font-black">{object?.action ?? String(action)}</p>{object?.priority && <div className="mt-2"><StatusBadge text={`${object.priority} priority`} tone={object.priority === "HIGH" ? "red" : object.priority === "MEDIUM" ? "amber" : "blue"} /></div>}{object?.rationale && <p className="mt-3 text-xs leading-5 text-[#656a75]">{object.rationale}</p>}</div>; })}</div></Panel>
      <div className="mt-5"><Link href={`/incidents/${detail.incident.id}`} className="inline-flex rounded-full bg-[#111625] px-5 py-3 text-xs font-black text-white">View full incident timeline →</Link></div>
    </div>
  );
}

function ContentCard({ icon: Icon, title, text, items, tone }: { icon: ComponentType<{ className?: string }>; title: string; text?: string; items?: string[]; tone: "blue" | "red" | "green" | "amber" | "pink" }) {
  const styles = { blue: "bg-[#edf0ff] text-[#5364db]", red: "bg-[#fff0ec] text-[#d94d43]", green: "bg-[#eaf8f0] text-[#16875d]", amber: "bg-[#fff4d1] text-[#a56a08]", pink: "bg-[#fdebf5] text-[#c73f82]" };
  return <Panel className="p-5"><div className="flex items-center gap-3"><div className={`flex h-10 w-10 items-center justify-center rounded-2xl ${styles[tone]}`}><Icon className="h-4.5 w-4.5" /></div><p className="text-sm font-black">{title}</p></div>{text && <p className="mt-4 text-sm leading-6 text-[#5f6470]">{text}</p>}{items && <div className="mt-4 space-y-2">{items.map((item, index) => <p key={index} className="text-xs leading-5 text-[#656a75]">• {item}</p>)}</div>}</Panel>;
}
