import Link from "next/link";

import {
  ArrowLeft,
  BookOpen,
  CheckCircle2,
  Lightbulb,
  ShieldAlert,
  Target,
} from "lucide-react";

import {
  notFound,
} from "next/navigation";

import {
  getDashboardIncidentDetail,
} from "@/lib/aegisops";


export const instant = false;


export default async function PostmortemDetailPage({
  params,
}: {
  params: Promise<{
    id: string;
  }>;
}) {
  const {
    id,
  } = await params;


  const incidentId =
    Number(id);


  const detail =
    await getDashboardIncidentDetail(
      incidentId
    );


  if (
    !detail ||
    !detail.postmortem
  ) {
    notFound();
  }


  const postmortem =
    detail.postmortem;


  return (
    <main className="p-6 xl:p-8">

      <div className="mx-auto max-w-[1500px]">

        <Link
          href="/postmortems"
          className="
            mb-5
            inline-flex
            items-center
            gap-2
            text-sm
            font-semibold
            text-slate-600
          "
        >
          <ArrowLeft className="h-4 w-4" />
          Postmortems
        </Link>


        <GlassPanel className="p-6">

          <div
            className="
              flex
              items-start
              gap-4
            "
          >

            <div
              className="
                flex
                h-12
                w-12
                shrink-0
                items-center
                justify-center
                rounded-2xl
                bg-violet-100/60
              "
            >
              <BookOpen
                className="
                  h-6
                  w-6
                  text-violet-600
                "
              />
            </div>


            <div>

              <p
                className="
                  text-xs
                  font-semibold
                  uppercase
                  tracking-wide
                  text-slate-500
                "
              >
                Incident #
                {
                  detail.incident.id
                }
              </p>


              <h1
                className="
                  mt-1
                  text-3xl
                  font-bold
                  tracking-tight
                "
              >
                {
                  detail.incident.title
                }
              </h1>


              <p
                className="
                  mt-2
                  text-sm
                  text-slate-600
                "
              >
                Generated by{" "}
                {postmortem.model}
              </p>

            </div>

          </div>

        </GlassPanel>


        <section
          className="
            mt-5
            grid
            gap-5
            lg:grid-cols-2
          "
        >

          <ContentCard
            icon={BookOpen}
            title="Summary"
            text={
              postmortem.summary
            }
          />


          <ContentCard
            icon={Target}
            title="Impact"
            text={
              postmortem.impact
              ?? "No impact summary."
            }
          />


          <ContentCard
            icon={ShieldAlert}
            title="Probable Root Cause"
            text={
              postmortem.root_cause
              ?? "Undetermined from available evidence."
            }
          />


          <ContentCard
            icon={CheckCircle2}
            title="What Went Well"
            items={
              postmortem
                .what_went_well
            }
          />


          <ContentCard
            icon={ShieldAlert}
            title="What Could Be Improved"
            items={
              postmortem
                .what_went_wrong
            }
          />


          <ContentCard
            icon={Lightbulb}
            title="Lessons Learned"
            items={
              postmortem
                .lessons_learned
            }
          />

        </section>


        <GlassPanel className="mt-5 p-6">

          <h2
            className="
              text-xl
              font-semibold
            "
          >
            Preventive Actions
          </h2>


          <div
            className="
              mt-5
              grid
              gap-4
              lg:grid-cols-2
            "
          >

            {
              postmortem
                .preventive_actions
                .map(
                  (
                    action,
                    index
                  ) => {

                    const object =
                      typeof action ===
                      "string"
                        ? null
                        : action;


                    return (
                      <div
                        key={index}
                        className="
                          rounded-2xl
                          border
                          border-white/30
                          bg-white/14
                          p-5
                        "
                      >

                        <p
                          className="
                            font-semibold
                            text-slate-900
                          "
                        >
                          {
                            object
                              ?.action
                            ?? String(action)
                          }
                        </p>


                        {object
                          ?.priority && (

                          <p
                            className="
                              mt-2
                              text-xs
                              font-semibold
                              text-indigo-700
                            "
                          >
                            Priority:{" "}
                            {
                              object
                                .priority
                            }
                          </p>

                        )}


                        {object
                          ?.rationale && (

                          <p
                            className="
                              mt-3
                              text-sm
                              leading-6
                              text-slate-600
                            "
                          >
                            {
                              object
                                .rationale
                            }
                          </p>

                        )}

                      </div>
                    );
                  }
                )
            }

          </div>

        </GlassPanel>


        <div className="mt-5">

          <Link
            href={
              `/incidents/${detail.incident.id}`
            }
            className="
              inline-flex
              rounded-full
              bg-indigo-100/60
              px-4
              py-2
              text-sm
              font-semibold
              text-indigo-700
            "
          >
            View full incident timeline →
          </Link>

        </div>

      </div>

    </main>
  );
}


function GlassPanel({
  children,
  className = "",
}: {
  children:
    React.ReactNode;

  className?:
    string;
}) {
  return (
    <section
      className={`
        rounded-[28px]
        border
        border-white/35
        ${className}
      `}
      style={{
        background:
          "rgba(255,255,255,.28)",

        backdropFilter:
          "blur(22px)",
      }}
    >
      {children}
    </section>
  );
}


function ContentCard({
  icon: Icon,
  title,
  text,
  items,
}: {
  icon:
    React.ComponentType<{
      className?: string;
    }>;

  title:
    string;

  text?:
    string;

  items?:
    string[];
}) {
  return (
    <GlassPanel className="p-5">

      <div
        className="
          flex
          items-center
          gap-3
        "
      >
        <div
          className="
            flex
            h-10
            w-10
            items-center
            justify-center
            rounded-2xl
            bg-indigo-100/60
          "
        >
          <Icon
            className="
              h-5
              w-5
              text-indigo-600
            "
          />
        </div>

        <h2 className="font-semibold">
          {title}
        </h2>
      </div>


      {text && (
        <p
          className="
            mt-4
            text-sm
            leading-6
            text-slate-700
          "
        >
          {text}
        </p>
      )}


      {items && (
        <div className="mt-4 space-y-2">

          {items.map(
            (
              item,
              index
            ) => (
              <p
                key={index}
                className="
                  text-sm
                  leading-6
                  text-slate-700
                "
              >
                • {item}
              </p>
            )
          )}

        </div>
      )}

    </GlassPanel>
  );
}